version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    ports:
      - "4010:4010"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./mongo/.env
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: resources
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./resources:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - node

volumes:
  mongo_data:
